import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Денис и Кристина",
  // description: "Generated by create next app",
};

declare global {
  interface Window {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      Telegram: any;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
      >
        {children}
      </body>
    </html>
  );
}
