name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: NodeJS setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.1

      - name: Dependecy installation
        run: npm install

      - name: App start
        run: npm run build

      - name: Deploy prod
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages

